### ISSUE TITLE
Error while running the project locally

### ISSUE THREAD

**Issue by jayasuryasakamuri** [philipwalton/responsive-components#2]
`'serve' errored after 2.41 s
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! responsive-components@ start: 'gulp serve'
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the responsive-components@ start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:`

**Comment by philipwalton** [comment]
Can you give me more details?

What command did you run that gave this error? Can you report the full error (what you've pasted here isn't enough to diagnose the problem)?

**Comment by jayasuryasakamuri** [comment]
I used the following commands
1. sudo npm install 
2.npm start

after npm start the following error came:-

![screenshot from 2018-03-01 23-18-33](https://user-images.githubusercontent.com/30170029/36860372-11d0624e-1da7-11e8-9cea-9bf1e0f4223b.png)

**Comment by philipwalton** [comment]
From that error message it looks like you already have something running on port 8080. If you shut down that thing, it should work.

I'm going to close this for now, but feel free to comment if it still doesn't work.
