### ISSUE TITLE
using the _resize-observer.html with template engines

### ISSUE THREAD

**Issue by yurifyodorov** [philipwalton/responsive-components#5]
The strategy of "container requests" using Resize Observer is excellent!

Having studied the repository [responsive-components](https://github.com/philipwalton/responsive-components), I assumed that you use the template language Nunjucks. I can not understand how you insert this script in the markup?

![script](https://user-images.githubusercontent.com/33720649/50790846-1d447000-12d1-11e9-82bd-3fdd6b023097.png)

### I do as follows:

`project`
`app | > index.html ` _(compiled)_
` `
`src | > templates > layout.njk` _(here I connect the script)_
`................... parts > resize-observer.njk ` _(script for resizeObserver)_
` `
`... | > pages > index.njk ` _(page template)_

My repository: [https://github.com/YuriFedorov/components](https://github.com/YuriFedorov/components)

**layout.njk**
_add block to end of the page_

![layout-njk](https://user-images.githubusercontent.com/33720649/50791797-eae84200-12d3-11e9-8c40-eedc21c2611e.png)

**index.njk**
_link to the file with the script_

![index-njk](https://user-images.githubusercontent.com/33720649/50792101-eb350d00-12d4-11e9-94c9-e37d55568354.png)

**resize-observer.njk**
_script from [here](https://github.com/philipwalton/responsive-components/blob/master/app/templates/_resize-observer.html)_

![resize-observer](https://user-images.githubusercontent.com/33720649/50792293-7dd5ac00-12d5-11e9-89c0-c48a0606c07f.png)

Gulp generates error while building:

![error](https://user-images.githubusercontent.com/33720649/50792541-6519c600-12d6-11e9-8631-92ffa51f689e.png)

What am I doing wrong? When connecting HTML fragments all is well.

**Comment by philipwalton** [comment]
Did you close this because you figured it out?

**Comment by yurifyodorov** [comment]
Yes, thanks. I solved it.
Just used the code from [this article](https://philipwalton.com/articles/responsive-components-a-solution-to-the-container-queries-problem/) and the error disappeared.
