### ISSUE TITLE
I need to add a condition where the script will not execute

### ISSUE THREAD

**Issue by yurifyodorov** [philipwalton/responsive-components#6]
In[ your script](https://github.com/philipwalton/responsive-components/blob/master/app/templates/_resize-observer.html), there is a snippet that searches for elements with the attribute `data-observe-resizes`:

    // Observe all non-custom element containers, i.e. all elements with the
    // `data-observe-resizes` attribute. Note: custom element containers
    // are observed via the connectedCallback() lifecycle method.

    var elements = document.querySelectorAll('[data-observe-resizes]');
    for (var element, i = 0; element = elements[i]; i++) {
      ro.observe(element);
    }

**Is it possible to add such a condition?**
If the container with the `data-observe-resize` attribute is inside the `<pre>` tags, the script should not run.

I use the [SyntaxHighlighter](https://yurifedorov.github.io/components/tile.html) library to style the code examples. I want that in examples there were no classes `" SM MD LG XL"`.

![demo](https://user-images.githubusercontent.com/33720649/51088111-e8bb3300-176c-11e9-9fea-ffbedb3c6b97.png)

**example in VSCode**

![pre](https://user-images.githubusercontent.com/33720649/51089217-9d0f8600-177a-11e9-9660-ab80ce727f33.png)

**Comment by philipwalton** [comment]
Yes, this is certainly possible. You'd just have to modify the `querySelectorAll()` call to a query that meets your needs.

**Comment by yurifyodorov** [comment]
Classes not in sight, exellent! Everything was so simple. Thanks for the tip.
Now I choose only `<div>` with `data-observe-resizes` attribute.

`var elements = document.querySelector('div, [data-observe-resizes]');`

There are still extra characters left in the examples `=""`.  I did not find a line in the script that is responsible for this.
![resize](https://user-images.githubusercontent.com/33720649/52034330-3a1f3c80-2539-11e9-8782-f2415fae8c7b.jpg)

**Comment by philipwalton** [comment]
I'm not sure, maybe your template system is generating them?

If you look at the [source](view-source:https://philipwalton.github.io/responsive-components/) for my demo site, you don't see any empty attributes, so it's not the code I'm using that's causing those for you.

**Comment by yurifyodorov** [comment]
You're right! If no attributes are specified in the tag, `=""` is not added. 
"[SyntaxHighlighter](http://alexgorbatchev.com/SyntaxHighlighter/manual/configuration/)" adds them precisely. I'll try to find out the reason.

You for syntax highlighting use the library ['highlight.js](https://highlightjs.org)' ?

![example](https://user-images.githubusercontent.com/33720649/52123008-df1f3f80-2635-11e9-9cb2-1f0dea575d7a.jpg)
